In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv("/content/temps.csv")
dataset

year  month  day   week  temp_2  temp_1  average  actual  forecast_noaa  \
0    2016      1    1    Fri      45      45     45.6      45             43   
1    2016      1    2    Sat      44      45     45.7      44             41   
2    2016      1    3    Sun      45      44     45.8      41             43   
3    2016      1    4    Mon      44      41     45.9      40             44   
4    2016      1    5   Tues      41      40     46.0      44             46   
..    ...    ...  ...    ...     ...     ...      ...     ...            ...   
343  2016     12   27   Tues      42      42     45.2      47             41   
344  2016     12   28    Wed      42      47     45.3      48             41   
345  2016     12   29  Thurs      47      48     45.3      48             43   
346  2016     12   30    Fri      48      48     45.4      57             44   
347  2016     12   31    Sat      48      57     45.5      40             42   

     forecast_acc  forecast_under  friend  
0              50              44      29  
1              50              44      61  
2              46              47      56  
3              48              46      53  
4              46              46      41  
..            ...             ...     ...  
343            50              47      47  
344            49              44      58  
345            50              45      65  
346            46              44      42  
347            48              47      57  

[348 rows x 12 columns]

In [ ]:
dataset.head(5)

year  month  day  week  temp_2  temp_1  average  actual  forecast_noaa  \
0  2016      1    1   Fri      45      45     45.6      45             43   
1  2016      1    2   Sat      44      45     45.7      44             41   
2  2016      1    3   Sun      45      44     45.8      41             43   
3  2016      1    4   Mon      44      41     45.9      40             44   
4  2016      1    5  Tues      41      40     46.0      44             46   

   forecast_acc  forecast_under  friend  
0            50              44      29  
1            50              44      61  
2            46              47      56  
3            48              46      53  
4            46              46      41

In [ ]:
dataset.shape

(348, 12)

In [ ]:
#one hot encoding
dataset = pd.get_dummies(dataset)
dataset

year  month  day  temp_2  temp_1  average  actual  forecast_noaa  \
0    2016      1    1      45      45     45.6      45             43   
1    2016      1    2      44      45     45.7      44             41   
2    2016      1    3      45      44     45.8      41             43   
3    2016      1    4      44      41     45.9      40             44   
4    2016      1    5      41      40     46.0      44             46   
..    ...    ...  ...     ...     ...      ...     ...            ...   
343  2016     12   27      42      42     45.2      47             41   
344  2016     12   28      42      47     45.3      48             41   
345  2016     12   29      47      48     45.3      48             43   
346  2016     12   30      48      48     45.4      57             44   
347  2016     12   31      48      57     45.5      40             42   

     forecast_acc  forecast_under  friend  week_Fri  week_Mon  week_Sat  \
0              50              44      29         1         0         0   
1              50              44      61         0         0         1   
2              46              47      56         0         0         0   
3              48              46      53         0         1         0   
4              46              46      41         0         0         0   
..            ...             ...     ...       ...       ...       ...   
343            50              47      47         0         0         0   
344            49              44      58         0         0         0   
345            50              45      65         0         0         0   
346            46              44      42         1         0         0   
347            48              47      57         0         0         1   

     week_Sun  week_Thurs  week_Tues  week_Wed  
0           0           0          0         0  
1           0           0          0         0  
2           1           0          0         0  
3           0           0          0         0  
4           0           0          1         0  
..        ...         ...        ...       ...  
343         0           0          1         0  
344         0           0          0         1  
345         0           1          0         0  
346         0           0          0         0  
347         0           0          0         0  

[348 rows x 18 columns]

In [ ]:
dataset.shape


(348, 18)

In [ ]:
#separate feature and labels
labels = np.array(dataset['actual'])
features = dataset.drop('actual',axis=1)
features =np.array(features)
features.shape

(348, 17)

In [ ]:
from sklearn.model_selection import train_test_split
train_features,test_feature,train_labels,test_labels = train_test_split(features,labels,test_size =0.20)

In [ ]:
#train the model
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=1000)


In [ ]:
rf.fit(train_features,train_labels)


RandomForestRegressor(n_estimators=1000)

In [ ]:
prediction = rf.predict(test_feature)
prediction

array([70.266, 52.106, 57.224, 69.367, 55.97 , 71.982, 77.431, 76.851,
       65.233, 48.055, 56.884, 66.476, 80.713, 66.92 , 63.226, 75.703,
       72.115, 67.458, 52.218, 68.674, 45.3  , 43.752, 70.67 , 41.882,
       41.953, 74.574, 61.951, 52.417, 80.541, 40.722, 64.086, 57.489,
       80.923, 69.1  , 61.058, 72.787, 76.944, 56.86 , 57.653, 59.382,
       62.447, 55.387, 50.547, 61.569, 61.873, 74.121, 58.55 , 60.067,
       62.719, 80.55 , 47.244, 67.379, 43.217, 81.543, 73.629, 41.64 ,
       72.396, 59.523, 69.818, 63.659, 52.818, 73.54 , 57.645, 53.87 ,
       51.984, 55.986, 63.675, 61.877, 73.52 , 75.754])

In [ ]:
errors = abs(prediction-test_labels)
errors

array([ 3.266,  4.106,  2.224,  0.367,  0.03 ,  6.018,  3.431, 10.149,
        1.233,  8.055,  3.884,  0.476,  4.713,  1.08 ,  2.774,  7.703,
        4.885,  4.542,  3.218,  4.674,  1.3  ,  4.248,  0.33 ,  1.882,
        1.953,  0.426,  3.951,  0.417,  7.541,  0.278,  1.086,  5.511,
        2.077, 10.9  ,  5.058,  2.213,  0.056,  1.86 ,  4.653,  0.618,
        2.553,  4.387,  0.453,  9.431,  6.127,  2.121,  2.55 ,  3.933,
        5.281,  1.55 ,  4.756,  0.379,  1.217,  3.457,  2.371,  9.36 ,
        6.396,  4.523,  1.182,  0.659,  4.182,  2.54 ,  6.355,  5.87 ,
        0.016,  2.986,  0.675,  1.877,  1.48 ,  3.246])

In [ ]:
mae = (errors/test_labels)
mae

array([0.04874627, 0.08554167, 0.04043636, 0.00531884, 0.00053571,
       0.07715385, 0.04636486, 0.11665517, 0.01926563, 0.201375  ,
       0.07328302, 0.00721212, 0.06201316, 0.01588235, 0.0420303 ,
       0.11327941, 0.06344156, 0.06308333, 0.06567347, 0.07303125,
       0.02954545, 0.0885    , 0.00464789, 0.04705   , 0.048825  ,
       0.00568   , 0.06812069, 0.00801923, 0.10330137, 0.00678049,
       0.0172381 , 0.08747619, 0.0250241 , 0.13625   , 0.09032143,
       0.02950667, 0.00072727, 0.03381818, 0.08779245, 0.0103    ,
       0.03927692, 0.08601961, 0.00888235, 0.13283099, 0.09010294,
       0.02945833, 0.04553571, 0.06145312, 0.07766176, 0.01962025,
       0.09146154, 0.00565672, 0.02897619, 0.04067059, 0.03119737,
       0.18352941, 0.09690909, 0.08223636, 0.01664789, 0.01046032,
       0.07336842, 0.03577465, 0.09929687, 0.12229167, 0.00030769,
       0.05633962, 0.01071429, 0.03128333, 0.01973333, 0.04108861])

In [ ]:
accuracy = (1-np.mean(mae))*100
accuracy

94.54566599444662

In [ ]:
from sklearn.tree import export_graphviz
tree = rf.estimators_[50]
export_graphviz(tree,out_file='tree.dot')

In [ ]:
import pydot
(graph,)=pydot.graph_from_dot_file('tree.dot')

In [ ]:
graph.write_png('tree.png')